INSERT INTO hourly_challenges (hour, title, description) VALUES
(6, 'Morning Gratitude', 'Share a photo of something you''re grateful for this morning.'),
(7, 'Sunrise Moment', 'Capture the sunrise or the early morning light.'),
(8, 'Healthy Breakfast', 'Show off your nutritious breakfast.'),
(9, 'First Smile of the Day', 'Share a selfie of your first real smile today.'),
(10, 'Mindful Minute', 'Take a 60-second video of a peaceful scene around you.'),
(11, 'Act of Kindness', 'Do something kind for someone and share the story.'),
(12, 'Lunchtime Energizer', 'Share what you''re eating to power through the day.'),
(13, 'Midday Stretch', 'Post a photo or short video of you taking a stretch break.'),
(14, 'Nature Appreciation', 'Find a piece of nature and share its beauty.'),
(15, 'Positive Affirmation', 'Share a positive affirmation that resonates with you.'),
(16, 'Creative Corner', 'Show something you''re creating, whether it''s art, music, or code.'),
(17, 'Hydration Check', 'Share a picture of your water bottle as a reminder to hydrate.'),
(18, 'Golden Hour Glow', 'Capture the beauty of the golden hour before sunset.'),
(19, 'Dinner Delight', 'Share what you''re having for dinner.'),
(20, 'Evening Wind-Down', 'Show how you''re relaxing and winding down for the night.'),
(21, 'Reflect on the Day', 'Share one positive thing that happened today.'),
(22, 'Starry Night', 'Capture the night sky or a cozy evening scene before you rest.');
